<?php
namespace App\Controllers\superadministrator;
/**
* Auto Generated By TrigerIgniter v1
* Codeigniter Version 4.1.x
* Codeigniter Controller
**/
use App\Models\Master_model;
use App\Controllers\BaseController;

class Dashboard extends BaseController
{
    protected $masterModel;
    /**
     * Class constructor.
     */ 
    public function __construct()
    {
        $this->masterModel = new Master_model(); //Set Default Models Of this Controller
        $this->PageData = $this->defaultPage(); //Attribute Of this Page
        $this->Template = $this->defaultTemplate(); //Template Of this Page
        $this->pager = \Config\Services::pager(); // Pagination
        $this->validation =  \Config\Services::validation();
    }

    protected function onLoad(){
        parent::onLoad();
        $this->getLocale();
        
        // check access level
        if (! $this->access_allowed()) {
            session()->setFlashdata("ci_login_flash_message", lang("Errors.AccessDenied", [], $this->PageData->locale));
            session()->setFlashdata("ci_login_flash_message_type", "text-danger");
            throw new \CodeIgniter\Router\Exceptions\RedirectException();
        };
    
    }
    
    //ATRIBUTE OF THIS PAGE
    private function defaultPage()
    {
        return (object) [
            'parent' => 'superadministrator/Dashboard',
            'header' => (session("level") == NULL ? NULL : session("level") . " :: ") . 'Master', 
            'title' => 'Dashboard',
            'subtitle' => [
                'Dashboard' => 'superadministrator/Dashboard/index'
            ],
            'url' => 'superadministrator/Dashboard/index',
            'stylesheets' => [],
            'scripts' => [],
            'locale' => 'id',
            'access' => ['superadministrator']
        ];
    }

    //TEMPLATE OF THIS PAGE
    private function defaultTemplate()
    {
        return (object) [
            'container' => 'superadministrator/_templates/Container',
            'header' => 'superadministrator/_templates/header',
            'navbar' => 'superadministrator/_templates/navbar',
            'sidebar' => 'superadministrator/_templates/sidebar',
            'footer' => 'superadministrator/_templates/footer',
        ];
    }
    
    private function access_allowed(){
        $allowed = FALSE;
        if (count($this->PageData->access)==0) return TRUE;
        if (! session()->has("level"))  return FALSE;
        foreach ($this->PageData->access as $key => $value) {
            if(session("level")==$value){
                $allowed=TRUE;
                break;
            }
        };
        return $allowed;
    }

    //INDEX
    public function index()
    {
        $data = [
            'Page' => $this->PageData,
            'Template' => $this->Template
        ];
        return view('superadministrator/dashboard', $data);
    }    
    //ENDFUNCTION
}
