<?php
namespace App\Controllers\superadministrator;
/**
* Auto Generated By TrigerIgniter v1
* Codeigniter Version 4.1.x
* Codeigniter Controller
**/
require_once(APPPATH.'ThirdParty'.DIRECTORY_SEPARATOR.'mPDF'.DIRECTORY_SEPARATOR.'vendor'.DIRECTORY_SEPARATOR.'autoload.php');
use App\Models\Master_model;
use App\Controllers\BaseController;

class Master extends BaseController
{
    protected $model; //Default Models Of this Controler

    /**
     * Class constructor.
     */ 
    public function __construct()
    {
        $this->model = new Master_model(); //Set Default Models Of this Controller
        $this->PageData = $this->defaultPage(); //Attribute Of this Page
        $this->Template = $this->defaultTemplate(); //Template Of this Page
        $this->pager = \Config\Services::pager(); // Pagination
        $this->validation =  \Config\Services::validation();
    }

    protected function onLoad(){
        parent::onLoad();
        $this->getLocale();
        
        // check access level
        if (! $this->access_allowed()) {
            session()->setFlashdata("ci_login_flash_message", lang("Errors.AccessDenied", [], $this->PageData->locale));
            session()->setFlashdata("ci_login_flash_message_type", "text-danger");
            throw new \CodeIgniter\Router\Exceptions\RedirectException();
        };
    
    }
    
    //ATRIBUTE OF THIS PAGE
    private function defaultPage()
    {
        return (object) [
            'parent' => 'superadministrator/Master',
            'header' => (session("level") == NULL ? NULL : session("level") . " :: ") . 'Master', 
            'title' => 'Master',
            'subtitle' => [
                'Master' => 'superadministrator/Master/index'
            ],
            'url' => 'superadministrator/Master/index',
            'stylesheets' => [],
            'scripts' => [],
            'locale' => 'id',
            'access' => ['superadministrator']
        ];
    }

    //TEMPLATE OF THIS PAGE
    private function defaultTemplate()
    {
        return (object) [
            'container' => 'superadministrator/_templates/Container',
            'header' => 'superadministrator/_templates/header',
            'navbar' => 'superadministrator/_templates/navbar',
            'sidebar' => 'superadministrator/_templates/sidebar',
            'footer' => 'superadministrator/_templates/footer',
        ];
    }
    
    private function access_allowed(){
        $allowed = FALSE;
        if (count($this->PageData->access)==0) return TRUE;
        if (! session()->has("level"))  return FALSE;
        foreach ($this->PageData->access as $key => $value) {
            if(session("level")==$value){
                $allowed=TRUE;
                break;
            }
        };
        return $allowed;
    }

    //JSON_FUNCTION
    public function toJson($id = NULL)
    {
        $id = $id == NULL ? $this->request->getPostGet("indexer") : base64_decode(urldecode($id));
        $this->response->setContentType('application/json');

        if ($id != NULL) {
            $result = $this->model->getById($id);

            if ($result == FALSE) {
                $temp = [];
                foreach ($this->model->getFields() as $key => $value) {
                    $temp[$value] = NULL;
                };
                $result = (object) $temp;
            }
            $this->response->setHeader('Content-Type', 'application/json');
            return json_encode($result);
        }

        // Table sorting using GET var
        $sortcolumn = $this->request->getGetPost("sortcolumn");
        $sortorder = $this->request->getGetPost("sortorder");
        if ($sortcolumn != NULL) $sortcolumn = base64_decode($sortcolumn);
        if ($sortcolumn != NULL && $sortorder != NULL) {
            $sortorder = strtoupper($sortorder);
            if ($sortorder != "DESC" && $sortorder != "ASC") $sortorder = "ASC";
            if (in_array($sortcolumn, $this->model->getFields())) {
                $this->model->order = $sortorder;
                $this->model->columnIndex = $sortcolumn;
            } else {
                $sortcolumn = NULL;
                $sortorder = NULL;
            }
        }

        $keyword = $this->request->getGetPost("keyword");
        $totalrecord = $this->model->getData($keyword)->countAllResults();

        // How many data shows each page
        $perPage = $this->request->getPostGet("perPage");
        if ($perPage == NULL || $perPage <= 0) {
            $result = [
                'draw' => 0,
                'recordsTotal' => $totalrecord,
                'recordsFiltered' => $totalrecord,
                'keyword' => $keyword,
                'data' => $this->model->getData($keyword)->findAll()
            ];         
        }else {
            $page = $this->request->getGetPost("page");
            $page = $page <= 0 ? 1 : $page;

            $result = [
                'draw' => 0,
                'recordsTotal' => $totalrecord,
                'recordsFiltered' => $totalrecord,
                'perPage' => $perPage,
                'currentPage' => ($totalrecord / $perPage >= $page ? $page : max(floor($totalrecord / $perPage), 1)),
                'startIndex' => min(($page * $perPage) - ($perPage - 1), $totalrecord),
                'endIndex' => min(($perPage * $page), $totalrecord),
                'keyword' => $keyword,
                'data' => $this->model->getData($keyword)->paginate($perPage)
            ];
        }

        $this->response->setHeader('Content-Type', 'application/json');
        return json_encode($result);
    }

    //INDEX
    public function index()
    {
        //indexstart
        
        // Table sorting using GET var
        $sortcolumn = $this->request->getGetPost("sortcolumn");
        $sortorder = $this->request->getGetPost("sortorder");
        if ($sortcolumn == NULL || $sortorder == NULL){
            if (session()->has("sorting_table")) {
                if (session("sorting_table")==$this->model->table) {
                    $sortcolumn = session("sortcolumn");
                    $sortorder = session("sortorder");
                };
            };
        }else{
            $sortcolumn = base64_decode($sortcolumn);
        }
        if ($sortcolumn != NULL && $sortorder != NULL) {
            $sortorder = strtoupper($sortorder);
            if ($sortorder != "DESC" && $sortorder != "ASC") $sortorder = "ASC";
            if (in_array($sortcolumn, $this->model->getFields())){
                $this->model->order = $sortorder;
                $this->model->columnIndex = $sortcolumn;
                session()->set('sortcolumn', $sortcolumn);
                session()->set('sortorder', $sortorder);
                session()->set('sorting_table', $this->model->table);
            }else{
                $sortcolumn = NULL;
                $sortorder = NULL;
                session()->remove('sortcolumn');
                session()->remove('sortorder');
                session()->remove('sorting_table');
            }
        }

        // How many data shows each page
        $perPage = $this->request->getPostGet("perPage");
        if ($perPage == NULL) {
            if (session()->has("paging_table")) {
                if (session("paging_table")==$this->model->table) {
                    $perPage = session("perPage");
                };
            };
        };
        if ($perPage != NULL) {
            // Minimum data per-page = 2
            if ($perPage <= 0) $perPage = 2;
            session()->set('perPage', $perPage);
            session()->set('paging_table', $this->model->table);
        }else{
            // Default data per-page = 20
            $perPage = 20;
            session()->remove('paging_table');
            session()->remove('perPage');
        }

        $page = $this->request->getGet("page");
        $page = $page<=0?1:$page;
        $keyword = $this->request->getGetPost("keyword");
        $totalrecord = $this->model->getData($keyword)->countAllResults();

        $this->PageData->url = "superadministrator/Master/index";
        $this->PageData->subtitle = [
            $this->PageData->title => 'superadministrator/Master/index'
        ];

        $data = [
            'sortcolumn' => $sortcolumn,
            'sortorder' => $sortorder,
            'data' => $this->model->getData($keyword)->paginate($perPage),
            'perPage' => $perPage,
            'currentPage' => $page,
            'start' => min(($page*$perPage)-($perPage-1), $totalrecord),
            'end' => min(($perPage*$page), $totalrecord),
            'totalrecord' => $totalrecord,
            'pager' => $this->model->pager,
            'keyword' => $keyword,
            'Page' => $this->PageData,
            'Template' => $this->Template
        ];
        return view('superadministrator/master/master_list', $data);
        //endindex
    }

    //READfunction
    public function read($id=NULL)
    {
        $id = $id==NULL?$this->request->getPostGet("id"):base64_decode(urldecode($id));

        $this->PageData->title = "Master Detail";
        $this->PageData->header .= ' :: Detail';
        $this->PageData->subtitle = [
            'Master' => 'superadministrator/Master/index',
            'Detail' => 'superadministrator/Master/read/' . urlencode(base64_encode($id)),
        ];
        $this->PageData->url = "superadministrator/Master/read/" . urlencode(base64_encode($id));
        
        $dataFind = $this->model->getById($id);

        if($dataFind == FALSE || $id == NULL){
            session()->setFlashdata('ci_flash_message', lang("Errors.DataNotExist", [], $this->PageData->locale));
            session()->setFlashdata('ci_flash_message_type', ' alert-danger ');
            return redirect()->to(base_url($this->PageData->parent . '/index'));
        }
        $data = [
            'data' => $this->model->getById($id), //getById on data
            'Page' => $this->PageData,
            'Template' => $this->Template
        ];
        return view('superadministrator/master/master_read', $data);
    }

    //CREATEfunction
    public function create()
    {
        $this->PageData->header .= ' :: ' . lang("Default.CreateItem", [], $this->PageData->locale);
        $this->PageData->title = "Create Master";
        $this->PageData->subtitle = [
            'Master' => 'superadministrator/Master/index',
            lang("Default.CreateItem", [], $this->PageData->locale) => 'superadministrator/Master/create',
        ];
        $this->PageData->url = "superadministrator/Master/create";

        $data = [
            'data' => (object) [
                'id' => set_value('id'),
                'master_name' => set_value('master_name'),
                'category_id' => set_value('category_id'),
                'quantity' => set_value('quantity'),
                'date' => set_value('date'),
                'description' => set_value('description'),
            ],
            'action' => site_url($this->PageData->parent.'/createAction'),
            'Page' => $this->PageData,
            'Template' => $this->Template
        ];
        return view('superadministrator/master/master_form', $data);
    }
    
    //ACTIONCREATEfunction
    public function createAction()
    {
        if($this->isRequestValid() == FALSE){
            return $this->create();
        };

        $data = [
            // 'id' => $this->request->getPost('id'),
            'master_name' => $this->request->getPost('master_name'),
            'category_id' => $this->request->getPost('category_id'),
            'quantity' => $this->request->getPost('quantity'),
            'date' => $this->request->getPost('date'),
            'description' => $this->request->getPost('description'),
        ];
        
        $this->model->insert($data);
        session()->setFlashdata('ci_flash_message', lang("Default.CreateSuccess", [], $this->PageData->locale));
        session()->setFlashdata('ci_flash_message_type', ' alert-success ');
        return redirect()->to(base_url($this->PageData->parent . '/index'));
    }
    
    //UPDATEfunction
    public function update($id=NULL)
    {
        $id = $id == NULL ? $this->request->getPostGet("id") : base64_decode(urldecode($id));

        $this->PageData->header .= ' :: ' . lang("Default.UpdateItem", [], $this->PageData->locale);
        $this->PageData->title = "Update Master";
        $this->PageData->subtitle = [
            'Master' => 'superadministrator/Master/index',
            lang("Default.UpdateItem", [], $this->PageData->locale) => 'superadministrator/Master/update/' . urlencode(base64_encode($id)),
        ];
        $this->PageData->url = "superadministrator/Master/update/" . urlencode(base64_encode($id));

        $dataFind = $this->model->getById($id);

        if($dataFind == FALSE || $id == NULL){
            session()->setFlashdata('ci_flash_message', lang("Errors.DataNotExist", [], $this->PageData->locale));
            session()->setFlashdata('ci_flash_message_type', ' alert-danger ');
            return redirect()->to(base_url($this->PageData->parent . '/index'));
        }
        $data = [
            'data' => (object) [
                'id' => set_value('id', $dataFind->id),
                'master_name' => set_value('master_name', $dataFind->master_name),
                'category_id' => set_value('category_id', $dataFind->category_id),
                'quantity' => set_value('quantity', $dataFind->quantity),
                'date' => set_value('date', $dataFind->date),
                'description' => set_value('description', $dataFind->description),
            ],
            'action' => site_url($this->PageData->parent.'/updateAction'),
            'Page' => $this->PageData,
            'Template' => $this->Template
        ];
        return view('superadministrator/master/master_form', $data);
    }
    
    //ACTIONUPDATEfunction
    public function updateAction()
    {
        $id = $this->request->getPostGet('oldid');
        $dataFind = $this->model->getById($id);

        if($dataFind == FALSE || $id == NULL){
            session()->setFlashdata('ci_flash_message', lang("Errors.DataNotExist", [], $this->PageData->locale));
            session()->setFlashdata('ci_flash_message_type', ' alert-danger ');
            return redirect()->to(base_url($this->PageData->parent . '/index'));
        };

        if($this->isRequestValid() == FALSE){
            return $this->update(urlencode(base64_encode($id)));
        };

        $data = [
            // 'id' => $this->request->getPost('id'),
            'master_name' => $this->request->getPost('master_name'),
            'category_id' => $this->request->getPost('category_id'),
            'quantity' => $this->request->getPost('quantity'),
            'date' => $this->request->getPost('date'),
            'description' => $this->request->getPost('description'),
        ];
        
        $this->model->update($id, $data);
        session()->setFlashdata('ci_flash_message', lang("Default.UpdateSuccess", [], $this->PageData->locale));
        session()->setFlashdata('ci_flash_message_type', ' alert-success ');
        return redirect()->to(base_url($this->PageData->parent . '/index'));
    }

    //DELETE
    public function delete($id=NULL)
    {
        $id = $id == NULL ? $this->request->getPostGet("id") : base64_decode(urldecode($id));
        $row = $this->model->getById($id);

        if ($row && $id != NULL) {
            
            
            $this->model->delete($id);
            session()->setFlashdata('ci_flash_message', lang("Default.DeleteSuccess", [], $this->PageData->locale));
            session()->setFlashdata('ci_flash_message_type', ' alert-success ');
            return redirect()->to(base_url($this->PageData->parent . '/index'));
        } else {
            session()->setFlashdata('ci_flash_message', lang("Errors.DataNotExist", [], $this->PageData->locale));
            session()->setFlashdata('ci_flash_message_type', ' alert-danger ');
            return redirect()->to(base_url($this->PageData->parent . '/index'));
        }
    }

    //DELETEBATCH
    public function deleteBatch()
    {
        $arr = $this->request->getPost("removeme");
        $res = 0;
        if ($arr!=NULL) {
            if (count($arr)>=1) {
                foreach ($arr as $key => $id) {
                    $row = $this->model->getById($id);
                    if (! $row || $id == NULL) continue;
                    
                    $this->model->delete($id);
                    $res++;
                }
            }
        }

        session()->setFlashdata('ci_flash_message', lang("Default.BatchDeleteSuccess", ["total"=>$res], $this->PageData->locale));
        session()->setFlashdata('ci_flash_message_type', ' alert-success ');
        return redirect()->to(base_url($this->PageData->parent . '/index'));
    }

    //TRUNCATE
    public function truncate()
    {
        $this->model->truncate();
        session()->setFlashdata('ci_flash_message', lang("Default.TruncateSuccess", [], $this->PageData->locale));
        session()->setFlashdata('ci_flash_message_type', ' alert-success ');
        return redirect()->to(base_url($this->PageData->parent . '/index'));
    }

    // FORMVALIDATION
    private function isRequestValid(){
        $res = FALSE;

        $this->validation->setRules([
                'master_name' => 'trim|required|max_length[250]',
                'category_id' => 'trim|required|max_length[11]',
                'quantity' => 'trim|required|min_length[1]|max_length[15]',
                'date' => 'trim|max_length[11]',
                'description' => 'trim|max_length[65535]',
        ]);

        if ($this->validation->withRequest($this->request)->run() == TRUE) {
            $res = TRUE;
        }else{
            $errors = $this->validation->getErrors();
            foreach ($errors as $key => $value) {
                session()->setFlashdata('ci_flash_message_'.$key, $value);
                session()->setFlashdata('ci_flash_message_'.$key.'_type', ' alert-danger ');
            }
        }
        return $res;
    }

    //EXPORTEXCELfunction
    public function toExcel(){
        $excel = new Master_model();
        $sortcolumn = $this->request->getGetPost("sortcolumn");
        $sortorder = $this->request->getGetPost("sortorder");
        if ($sortcolumn == NULL && $sortorder == NULL){
            if (session()->has("sorting_table")) {
                if (session("sorting_table")==$this->model->table) {
                    $sortcolumn = session("sortcolumn");
                    $sortorder = session("sortorder");
                };
            };
        };
        if ($sortcolumn != NULL && $sortorder != NULL) {
            $excel->order = $sortorder;
            $excel->columnIndex = $sortcolumn;
        };

        // Redirect output to a client’s web browser (Xlsx)
        $this->response->setContentType('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        $this->response->setHeader('Content-Disposition', 'attachment;filename="Assets ' . date("Y") . '.xlsx"');
        // If you're serving to IE 9, then the following may be needed
        $cacheOptions = [
            'max-age'  => 1,
            's-maxage' => 900,
            'etag'     => 'excel_Assets'
        ];
        $this->response->setCache($cacheOptions);
        // If you're serving to IE over SSL, then the following may be needed
        $this->response->setHeader('Expires', 'Mon, 26 Jul 1997 05:00:00 GMT');
        $this->response->setLastModified(gmdate('D, d M Y H:i:s') . ' GMT');
        $this->response->setHeader('Cache-Control', 'cache')->appendHeader('Cache-Control', 'must-revalidate'); // HTTP/1.1
        $this->response->setHeader('Pragma', 'public'); // HTTP/1.0
        $excel->export();
    }

    //IMPORTEXCELfunction
    public function fromExcel(){
        $filename = NULL;
        if ($excelfile = $this->request->getFile('excel_file')) {
            if ($excelfile->isValid()) {
                if (!$excelfile->hasMoved()) {
                    $fotonewName = $excelfile->getRandomName();
                    $excelfile->move(WRITEPATH . 'uploads', $fotonewName);
                }
                $filename = WRITEPATH . 'uploads/' . $excelfile->getName();
            } else {
                session()->setFlashdata('ci_flash_message', $excelfile->getErrorString() . ' (' . $excelfile->getError() . ')');
                session()->setFlashdata('ci_flash_message_type', ' text-danger ');
                return $this->index();
            };
        };
        $excel = new Master_model();
        $result = $excel->import($filename);
        session()->setFlashdata('ci_flash_message', lang("Default.ImportedData", ["total"=>$result], $this->PageData->locale));
        session()->setFlashdata('ci_flash_message_type', ' alert-primary ');
        safeUnlink($filename);
        return redirect()->to(base_url($this->PageData->parent . '/index'));
    }

    //EXPORTWORDfunction
    public function toWord()
    {
        $this->response->setContentType('application/vnd.ms-word');
        $this->response->setHeader('Content-Disposition', 'attachment;filename="Assets ' . date("Y") . '.doc"');

        // Table sorting using GET var
        $sortcolumn = $this->request->getGetPost("sortcolumn");
        $sortorder = $this->request->getGetPost("sortorder");
        if ($sortcolumn == NULL || $sortorder == NULL){
            if (session()->has("sorting_table")) {
                if (session("sorting_table")==$this->model->table) {
                    $sortcolumn = session("sortcolumn");
                    $sortorder = session("sortorder");
                };
            };
        }else{
            $sortcolumn = base64_decode($sortcolumn);
        }
        if ($sortcolumn != NULL && $sortorder != NULL) {
            if ($sortorder != "DESC" && $sortorder != "ASC") $sortorder = "ASC";
            if(in_array($sortcolumn, $this->model->getFields())){
                $this->model->order = $sortorder;
                $this->model->columnIndex = $sortcolumn;
            }
        }

        $this->PageData->title = "Word Document File";
        $this->PageData->subtitle = ["Master", "Word  Document File"];

        $data = array(
            'Page' => $this->PageData,
            'data' => $this->model->sort()->findAll(),
            'start' => 0
        );
        
        return view('superadministrator/master/master_doc', $data);
    }

    //mPDF_EXPORT_FUNCTION
    public function toPdf(){
        // Table sorting using GET var
        $sortcolumn = $this->request->getGetPost("sortcolumn");
        $sortorder = $this->request->getGetPost("sortorder");
        if ($sortcolumn == NULL || $sortorder == NULL) {
            if (session()->has("sorting_table")) {
                if (session("sorting_table") == $this->model->table) {
                    $sortcolumn = session("sortcolumn");
                    $sortorder = session("sortorder");
                };
            };
        } else {
            $sortcolumn = base64_decode($sortcolumn);
        }
        if ($sortcolumn != NULL && $sortorder != NULL) {
            if ($sortorder != "DESC" && $sortorder != "ASC") $sortorder = "ASC";
            if (in_array($sortcolumn, $this->model->getFields())) {
                $this->model->order = $sortorder;
                $this->model->columnIndex = $sortcolumn;
            }
        }

        $this->PageData->title = "PDF File";
        $this->PageData->subtitle = ["Master", "PDF File"];

        $data = array(
            'Page' => $this->PageData,
            'data' => $this->model->sort()->findAll(),
            'start' => 0
        );

        $view = \Config\Services::renderer();
        $temp = $view->setData($data)->render('superadministrator/master/master_pdf');

        $tempDir = "temp";
        if(!file_exists($tempDir)) mkdir($tempDir);

        $mpdf = new \Mpdf\Mpdf([
            'orientation' => 'P',
            'tempDir' => $tempDir
        ]);
        $mdpfFilename = "Master " . date("d_m_Y") . ".pdf";
        $mpdf->WriteHTML($temp);

        $this->response->setContentType('application/pdf');
        $this->response->setHeader('Content-Disposition', 'attachment;filename="' . $mdpfFilename . '"');
        $mpdf->Output(); // opens in browser
    }

    //PRINTfunction
    public function printAll(){
        // Table sorting using GET var
        $sortcolumn = $this->request->getGetPost("sortcolumn");
        $sortorder = $this->request->getGetPost("sortorder");
        if ($sortcolumn == NULL || $sortorder == NULL){
            if (session()->has("sorting_table")) {
                if (session("sorting_table")==$this->model->table) {
                    $sortcolumn = session("sortcolumn");
                    $sortorder = session("sortorder");
                };
            };
        }else{
            $sortcolumn = base64_decode($sortcolumn);
        }
        if ($sortcolumn != NULL && $sortorder != NULL) {
            if ($sortorder != "DESC" && $sortorder != "ASC") $sortorder = "ASC";
            if(in_array($sortcolumn, $this->model->getFields())){
                $this->model->order = $sortorder;
                $this->model->columnIndex = $sortcolumn;
            }
        }

        $this->PageData->title = "Master Data";
        $this->PageData->subtitle = ["Master", "Print All"];
        $this->PageData->url = "superadministrator/Master/printAll/";

        $data = array(
            'Page' => $this->PageData,
            'data' => $this->model->sort()->findAll(),
            'start' => 0
        );
        
        return view('superadministrator/master/master_print', $data);
    }
    
    //ENDFUNCTION
}
